[versions]
sshj = "0.39.0"
asnOne = "0.6.0"
eddsa = "0.3.0"
bouncycastle = "1.78.1"
expectit = "0.9.0"
commonsIo = "2.11.0"
rundeckCore = "5.0.1-20240115"
slf4j = "1.7.36"
junit = "4.13.2"
groovy = "3.0.22"
spock = "2.0-groovy-3.0"
cglib = "3.3.0"
objenesis = "1.2"
axionRelease = "1.18.12"

[libraries]
sshj = { group = "com.hierynomus", name = "sshj", version.ref = "sshj" }
asnOne = { group = "com.hierynomus", name = "asn-one", version.ref = "asnOne" }
eddsa = { group = "net.i2p.crypto", name = "eddsa", version.ref = "eddsa" }
bcpkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bouncycastle" }
bcprov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
expectitCore = { group = "net.sf.expectit", name = "expectit-core", version.ref = "expectit" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commonsIo" }
rundeckCore = { group = "org.rundeck", name = "rundeck-core", version.ref = "rundeckCore" }
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
groovyAll = { group = "org.codehaus.groovy", name = "groovy-all", version.ref = "groovy" }
spockCore = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
cglibNodep = { group = "cglib", name = "cglib-nodep", version.ref = "cglib" }
objenesis = { group = "org.objenesis", name = "objenesis", version.ref = "objenesis" }

[bundles]
bouncycastle = ["bcpkix", "bcprov"]
testLibs = ["junit", "groovyAll", "spockCore", "cglibNodep", "objenesis"]

[plugins]
axionRelease = { id = "pl.allegro.tech.build.axion-release", version.ref = "axionRelease" }
